name: spark
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [spark]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "spark"
  spark:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
    - run: ls -la  
    
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin

    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.5.3'
        hadoop-version: '3'

    - run: spark-submit --version
    #- run: spark-submit --master local hello.py
    
    - name: Descargar dataset
      run: wget -O dataset.csv https://raw.githubusercontent.com/adsoftsito/bigdata/refs/heads/main/datasets/people.csv   
    
    - run: ls -la

    - name: Ejecutar Spark
      run: spark-submit --master local people.py 

    - name: Verificar contenido de results/
      run: ls -la results

    - name: GIT commit and push docs
      env: 
        CI_COMMIT_MESSAGE: save spark results
        CI_COMMIT_AUTHOR: dazayy00 
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "zs21020562@estudiantes.uv.mx"
        
        # Forzar inclusión de archivos en results/, incluso si están en .gitignore
        git add -f results/* 
        
        # Verificar si hay cambios antes de hacer commit
        if git diff --cached --quiet; then
          echo "No hay cambios para hacer commit"
        else
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
        fi
